project:
  type: website
  output-dir: docs

website:
  title: "Wendy Frankel"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: photos.qmd
        text: Photos

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false


